base_pkgs:
  - net-tools
  - htop
  - neovim
  - tmux
  - bind9-dnsutils
  - tree
  - iftop
  - ufw
  - gnupg
  - apt-transport-https
  - lsb-release
  - wget
  - debian-archive-keyring

locale: "en_US.UTF-8"
nonroot_username: "goss"
ansible_user: "{{ nonroot_username }}"
hostfile_path: "/inventory/hosts.ini"
# Every 4 hours
apt_cache_stale: 14400

bash_config:
  - { line: "set -o vi" }
  - { line: "HISTSIZE=100000", regexp: "^HISTSIZE=" }
  - { line: "HISTFILESIZE=200000", regexp: "^HISTFILESIZE=" }
  - { line: "shopt -s cmdhist" }

nats_version: "2.12.2"

nats_instances:
  - name: staging
    service_name: nats-server-staging
    port: 4223
    http_port: 8223
  - name: prod
    service_name: nats-server-prod
    port: 4224
    http_port: 8224

# NATS server, used in both archiver and collector configs
nats_server_addr_staging: "do-small-test:4223"

postgresql_version: "18"
timescaledb_database_name: "gossip_observer"
timescaledb_staging_database_name: "gossip_observer_staging"

# Binary staging directory for deployments
binary_staging_dir: "{{ playbook_dir }}/binaries"
