[package]
name = "gossip_archiver"
version = "0.1.0"
edition = "2024"

[dependencies]
flume = { version = "0.11", features = ["async"] }
tokio = { version = "1.47", features = ["full", "tracing"] }

anyhow = "1.0"

chrono = { version = "0.4", default-features = false, features = [
        "clock",
        "serde",
] }

async-nats = "0.42.0"
futures = "0.3.31"

async-duckdb = { git = "https://github.com/jharveyb/async-duckdb", branch = "bump_to_1_4_0", features = [
        "chrono",
        "uuid",
] }
bytes = { version = "1.10.1", features = ["serde"] }
console-subscriber = "0.4.1"
twox-hash = { version = "2.1.2", features = ["std", "xxhash3_64"] }
ahash = "0.8.12"
