---
- name: Configure Gossip Archiver servers
  hosts: archivers
  become: true

  pre_tasks:
    - name: Load vault variables
      ansible.builtin.include_vars: vault.yml

  tasks:
    - name: Gossip Archiver setup
      ansible.builtin.import_tasks: tasks/gossip_archiver.yml

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
