- name: Configure NATS servers
  hosts: nats
  # Tailscale SSH
  remote_user: "{{ nonroot_username }}"
  become: true

  tasks:
    - import_tasks: tasks/nats.yml

  handlers:
    - import_tasks: handlers/main.yml
