- name: Configure NATS servers
  hosts: nats
  # Tailscale SSH
  become: true

  tasks:
    - name: NATS setup
      ansible.builtin.import_tasks: tasks/nats.yml

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
