[package]
edition = "2024"
name    = "electrum-cli"
version = "0.1.0"

[dependencies]
anyhow          = "1.0"
bitcoin         = "0.32.4"
clap            = { version = "4.0", features = ["derive"] }
electrum-client = { version = "0.24.1", features = ["use-rustls"] }
serde_json      = "1.0.145"
