# Big VPS
# Opening Menu
"019c26b4-9efe-7333-9c5e-7b3336d9b733" = 10023

# Small VPS
# Team Corn
"019bfdbc-10b8-794f-91cb-132c5f4cc390" = 9854
# LNT hub 1
"019c26b5-3e05-7d13-91ab-182eb98219e1" = 10395
# LNT hub 2
"019c26b5-a344-7be0-91a5-8221c53446a2" = 2079
# Wizened
"019c26b8-3118-72db-9059-d0d7eab225ba" = 9696
# Big Chungus
"019c26b8-3137-7cb2-bf48-250a5ce79d8d" = 10772
# Balanced Hubs
"019c26b8-3148-759c-8494-454ce6b62c57" = 11489
# Jersey City 2
"019c26b8-315a-77b2-9e80-61f45ec40f15" = 495
# Jerset City 3
"019c26b8-31d4-7973-b55f-b6218e03d7ea" = 4231

# Medium VPS
# LNT leaf 1
"019c26b6-aff9-74e0-935f-0cd39683850f" = 6269
# LNT leaf 2
"019c26b7-1636-73e7-aa3b-a9ca4020d220" = 10420
# LIC 2
"019c26b8-3125-798a-afbf-cf3f308089cd" = 1880
# LIC 1
"019c26b8-316d-7d55-9e6d-18990aed72a2" = 9203
# Central-Adjacent
"019c26b8-3180-7332-b0fe-a48931990692" = 1008
# Level 2
"019c26b8-3191-7fff-895f-5ed752c53bdc" = 8165
# Brooklyn 2
"019c26b8-31a6-7954-9de7-881d681e742e" = 7153
# Lower East Side 2
"019c26b8-31b8-7cc9-bb95-1b0223d7b5b1" = 4200
# Brooklyn 3
"019c26b8-3219-7c9b-aa3f-312979fffa20" = 10959
# Brooklyn 2
"019c26b8-31e4-741f-9034-71f14cdb8753" = 7150
# Midsize
"019c26b8-31f2-7969-9266-3536fc515d27" = 5631
# Well Connected 
"019c26b8-3205-7c55-8236-24db921b665e" = 6636
# Unused
# "019c26b8-322c-7025-a6cf-a8eb273562c0"